# Generated by Django 3.2.5 on 2021-09-18 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('properties', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_sensor', models.CharField(choices=[('a', 'accel'), ('g', 'gyro'), ('c', 'compass'), ('ca', 'cam')], default='a', help_text='Device type', max_length=2)),
                ('schema', models.JSONField(default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.application')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('data', models.JSONField(default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.JSONField(default=dict)),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('file_format', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor')),
            ],
        ),
    ]
