# Generated by Django 3.2.5 on 2021-11-15 12:41

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Reading_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('data_file', models.FileField(upload_to='sensor_readings/%Y/%m/%d/')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.sensor')),
            ],
        ),
    ]
