# Generated by Django 3.2.5 on 2021-08-23 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_device_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='end_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='file',
            name='start_timestamp',
        ),
        migrations.AddField(
            model_name='file',
            name='file_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accel',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.device'),
        ),
        migrations.AlterField(
            model_name='sensor_reading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor'),
        ),
        migrations.CreateModel(
            name='Analytics_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor')),
            ],
        ),
    ]
