# Generated by Django 3.2.5 on 2021-07-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accel',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type_of_device',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_sensor', models.CharField(choices=[('a', 'accel'), ('g', 'gyro'), ('c', 'compass')], default='a', help_text='Device type', max_length=2)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.AddField(
            model_name='accel',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
            preserve_default=False,
        ),
    ]
