# Generated by Django 3.2.5 on 2021-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210726_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type_of_sensor',
            field=models.CharField(choices=[('a', 'accel'), ('g', 'gyro'), ('c', 'compass'), ('ca', 'cam')], default='a', help_text='Device type', max_length=2),
        ),
    ]
