# Generated by Django 3.2.5 on 2021-08-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210803_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='schema',
            field=models.JSONField(default={'error': 'no_data'}),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='data',
            field=models.JSONField(default={'error': 'no_data'}),
        ),
        migrations.CreateModel(
            name='Sensor_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField(default={'error': 'no_data'})),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.sensor')),
            ],
        ),
    ]
