# Generated by Django 3.2.5 on 2021-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210811_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='data',
            field=models.JSONField(default={'error': ''}),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='schema',
            field=models.JSONField(default={'error': ''}),
        ),
        migrations.AlterField(
            model_name='sensor_reading',
            name='data',
            field=models.JSONField(default={'error': ''}),
        ),
    ]
