# Generated by Django 3.2.5 on 2021-09-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
